# Generated by Django 3.2.3 on 2021-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
