# Generated by Django 3.2.3 on 2021-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210606_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='centerhead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='centerpara1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='firsthead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='firstpara1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='imagehead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='imagelinkc1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='imagepara1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='imgc1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='imgcalt1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='lastimg1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='lastimgalt1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='lastimglink1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list11',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list21',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list31',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list41',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list51',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='list61',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='listnpara1',
        ),
    ]
