# Generated by Django 3.2.3 on 2021-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210606_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keywords',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
