# Generated by Django 3.2.3 on 2021-06-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogsec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsec',
            old_name='author',
            new_name='author1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='authorlink',
            new_name='authorlink1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='date',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='field',
            new_name='field1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='firsthead',
            new_name='firsthead11',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='firstpara',
            new_name='firstpara11',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='keywords',
            new_name='keywords1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list1',
            new_name='list111',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list2',
            new_name='list211',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list3',
            new_name='list311',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list4',
            new_name='list411',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list5',
            new_name='list511',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='list6',
            new_name='list611',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='listnpara',
            new_name='listnpara11',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='mainalt',
            new_name='mainalt1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='mainimg',
            new_name='mainimg1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='mainimglink',
            new_name='mainimglink1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='postid',
            new_name='post_id1',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='subhead1',
            new_name='subhead111',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='subpara1',
            new_name='subpara111',
        ),
        migrations.RenameField(
            model_name='blogsec',
            old_name='thumbnail',
            new_name='thumbnail1',
        ),
    ]
